secret:
  mongodb_uri:
    username: yourusername
    password: yourpassword
    dbchart: database
    dbport: 27017
    dbconn: "guestbook?authSource=admin"
image:
  repository: phico/backend
  tag: "2.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  host: backend.minikube.local
